//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProj3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassroomAndLabPolicy
    {
        public int CLP_Id { get; set; }
        public string CLP_desc { get; set; }
        public Nullable<int> Syllabus_ID { get; set; }
    
        public virtual Syllab Syllab { get; set; }
        public virtual ClassroomAndLabPolicy ClassroomAndLabPolicies1 { get; set; }
        public virtual ClassroomAndLabPolicy ClassroomAndLabPolicy1 { get; set; }
    }
}
