//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProj3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseOutcome
    {
        public int CO_ID { get; set; }
        public string CO_Code { get; set; }
        public string CO_DESC { get; set; }
        public string CO_CVA { get; set; }
        public string CO_POactivated { get; set; }
        public string CO_DOLLevel { get; set; }
        public int Syllabus_ID { get; set; }
    
        public virtual CourseOutcome CourseOutcomes1 { get; set; }
        public virtual CourseOutcome CourseOutcome1 { get; set; }
        public virtual CourseOutcome CourseOutcomes11 { get; set; }
        public virtual CourseOutcome CourseOutcome2 { get; set; }
        public virtual CourseOutcome CourseOutcomes12 { get; set; }
        public virtual CourseOutcome CourseOutcome3 { get; set; }
        public virtual Syllab Syllab { get; set; }
    }
}
