//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProj3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDeliverableOutputsAndRequirement
    {
        public int CDOR_Id { get; set; }
        public string OutputReq { get; set; }
        public string OutputReqDesc { get; set; }
        public string Cilo_Add { get; set; }
        public string ToA { get; set; }
        public int Syllabus_ID { get; set; }
    
        public virtual CourseDeliverableOutputsAndRequirement CourseDeliverableOutputsAndRequirements1 { get; set; }
        public virtual CourseDeliverableOutputsAndRequirement CourseDeliverableOutputsAndRequirement1 { get; set; }
        public virtual CourseDeliverableOutputsAndRequirement CourseDeliverableOutputsAndRequirements11 { get; set; }
        public virtual CourseDeliverableOutputsAndRequirement CourseDeliverableOutputsAndRequirement2 { get; set; }
        public virtual Syllab Syllab { get; set; }
    }
}
