//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProj3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DMISEntitiesxx : DbContext
    {
        public DMISEntitiesxx()
            : base("name=DMISEntitiesxx")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassroomAndLabPolicy> ClassroomAndLabPolicies { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseDeliverableOutputsAndRequirement> CourseDeliverableOutputsAndRequirements { get; set; }
        public virtual DbSet<CourseOutcome> CourseOutcomes { get; set; }
        public virtual DbSet<GradingSystem> GradingSystems { get; set; }
        public virtual DbSet<LearningPlan> LearningPlans { get; set; }
        public virtual DbSet<PEO> PEOs { get; set; }
        public virtual DbSet<ProgramOutcome> ProgramOutcomes { get; set; }
        public virtual DbSet<Revision> Revisions { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<SciVid> SciVids { get; set; }
        public virtual DbSet<Syllab> Syllabs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Rubric> Rubrics { get; set; }
    }
}
