//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProj3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningPlan
    {
        public int LPlan_ID { get; set; }
        public string LPlan_Outcome { get; set; }
        public int LPlan_No_hours { get; set; }
        public string LPlan_Topics { get; set; }
        public string LPlan_Asses { get; set; }
        public int Syllabus_ID { get; set; }
        public string activityT { get; set; }
        public string activityL { get; set; }
    
        public virtual LearningPlan LearningPlan1 { get; set; }
        public virtual LearningPlan LearningPlan2 { get; set; }
        public virtual Syllab Syllab { get; set; }
    }
}
