//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProj3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramOutcome
    {
        public int PO_Id { get; set; }
        public string PO_Code { get; set; }
        public string PO_attr { get; set; }
        public string PO_Desc { get; set; }
        public string PO_CVA { get; set; }
        public int Syllabus_ID { get; set; }
    
        public virtual ProgramOutcome ProgramOutcome1 { get; set; }
        public virtual ProgramOutcome ProgramOutcome2 { get; set; }
        public virtual ProgramOutcome ProgramOutcome11 { get; set; }
        public virtual ProgramOutcome ProgramOutcome3 { get; set; }
        public virtual Syllab Syllab { get; set; }
    }
}
