//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProj3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision
    {
        public int ID { get; set; }
        public double Version { get; set; }
        public string Items { get; set; }
        public int User_ID { get; set; }
        public Nullable<System.DateTime> Rev_Date { get; set; }
        public Nullable<System.DateTime> App_Date { get; set; }
        public int Syllabus_ID { get; set; }
    
        public virtual Revision Revision1 { get; set; }
        public virtual Revision Revision2 { get; set; }
        public virtual Revision Revision11 { get; set; }
        public virtual Revision Revision3 { get; set; }
        public virtual Syllab Syllab { get; set; }
        public virtual User User { get; set; }
    }
}
