//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProj3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ID { get; set; }
        public Nullable<double> Time_S { get; set; }
        public Nullable<double> Time_E { get; set; }
        public string Day { get; set; }
        public Nullable<int> Room_ID { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
