//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProj3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SciVid
    {
        public int SciVid_ID { get; set; }
        public string Core_Val { get; set; }
        public string Attributes { get; set; }
        public int Syllabus_ID { get; set; }
    
        public virtual SciVid SciVid1 { get; set; }
        public virtual SciVid SciVid2 { get; set; }
        public virtual Syllab Syllab { get; set; }
    }
}
